[package]
name = "nivelesdeniveles-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
rocket = "0.5.1"
serde = "1.0.188"
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
dotenv = "0.15.0"

[dependencies.mongodb]
version = "3.1.0"
