import LocalizedStrings from 'react-localization';

export const Localizations = new LocalizedStrings({
 es:{
   slogan: "Llevando la seguridad de los colombianos a otro nivel!",
   knowButton: "Conóce nuestro proyecto",
   header1: "La prevención y la información es la clave",
   p1: "Niveles de Niveles es una plataforma que utiliza la prevención y la información como la herramienta más importante para combatir desastres naturales. Creamos un ambiente seguro donde los usuarios tienen la opción de reportar, ser alertados y estar informados sobre los niveles de riesgo de desastres naturales a su alrededor. Prepárate utilizando nuestra",
   guia:"guía para desastres",
   sensorsHeader: "Nuestros Sensores",
   sensorText:"Utilizamos sensores para medir el nivel del agua y el movimiento de la tierra y así determinar el riesgo de desbordamientos y deslizamientos.",
   crowdHeader: "Crowdsourcing",
   crowdText: "Utilizamos un modelo de colaboración abierta (crowdsourcing) para obtener los reportes de desastres de la misma población.",
   desastres: "Desastres Naturales",
   desastresHeader: "Los desastres que prevenimos son",
   desbordamientoHead: "Desbordamientos",
   desbordamientoText: "El desbordamiento de ríos, arroyos y otros cuerpos de agua causan inundaciones en diferentes municipios del Atlántico. Tener un mecanismo que alerte sobre estos les daría a las comunidades cercanas tiempo para recoger sus pertenencias más importantes y evitar daños mayores en sus viviendas. Para medir estos, utilizamos sensores ultrasónicos para medir el nivel del agua.",
   incendioHead: "Incendios Forestales",
   incendioText: "En el Caribe colombiano se han reportado 150 incendios forestales este año y su causa principal son las altas temperaturas y las escasas lluvias. Una vez que estos llegan a un punto que su magnitud es tan grande que puede llevar días para detenerlo, por lo que si logramos reportar estos en el menor tiempo posible, será más fácil evitar la destrucción de la fauna a su alrededor.",
   deslizamientoHead: "Deslizamientos",
   deslizamientoText: "Entre 1920 y 2020, se registraron más de 11.800 deslizamientos de tierra, pero solamente en 2022 se dieron 813. Esto es una prueba de cómo el cambio climático está afectando al país. Hay muchas personas que no saben que están en una zona de riesgo por lo que el tener una alerta sobre el movimiento de la tierra puede ayudar a las comunidades a evitar catástrofes. Utilizamos acelerómetros para medir el movimiento de la tierra.",
   recursos:"Recursos",
   recursosHead:"¿Te interesa? Mira un poco de nuestros avances",
   repo:"Nuestro Repositorio",
   politica:"Política de Privacidad",
   download: "Descárgalo en",
   equipo:"Equipo",
   equipoHead:"Cónoce al equipo Hacks Costeños",
   nathan:"Programación y Hardware",
   ashlee:"Web y Planeación",
   felipe:"Edición y Diseño",
   herramientas:"Herramientas",
   herramientasHead:"Tecnologías que utilizamos",
   enlaces:"Enlaces",
   inicio:"Inicio",
   mision:"Misión",
   nosotros:"Nosotros"
 },
 en: {
  slogan: "Taking the security of Colombians to another level!",
  knowButton: "Discover our project",
  header1: "Prevention and information are the key",
  p1: "Niveles de Niveles is a platform that uses prevention and information as the most important tools to combat natural disasters. We create a secure environment where users have the option to report, be alerted, and stay informed about the risk levels of natural disasters around them. Prepare yourself using our",
  guia:"disaster guide",
  sensorsHeader: "Our Sensors",
  sensorText:"We use sensors to measure water levels and earth movement to determine the risk of floods and landslides.",
  crowdHeader: "Crowdsourcing",
  crowdText: "We use an open collaboration model (crowdsourcing) to obtain disaster reports from the population itself.",
  desastres: "Natural Disasters",
  desastresHeader: "The disasters we prevent are",
  desbordamientoHead: "Overflow",
  desbordamientoText: "River, stream, and other water body overflows cause flooding in different municipalities in Atlántico. Having a mechanism that alerts about these would give nearby communities time to gather their most important belongings and avoid major damage to their homes. To measure these, we use ultrasonic sensors to measure water levels.",
  incendioHead: "Forest Fires",
  incendioText: "In the Colombian Caribbean, 150 forest fires have been reported this year, mainly caused by high temperatures and scarce rainfall. Once these fires reach a point where their magnitude is so large that it can take days to stop them, reporting them as quickly as possible will make it easier to prevent the destruction of the surrounding fauna.",
  deslizamientoHead: "Landslides",
  deslizamientoText: "Between 1920 and 2020, over 11,800 landslides were recorded, but only 813 occurred in 2022. This is evidence of how climate change is affecting the country. Many people are unaware that they are in a risk zone, so having an alert about earth movement can help communities avoid catastrophes. We use accelerometers to measure earth movement.",
  recursos:"Resources",
  recursosHead:"Interested? Take a look at some of our progress",
  repo:"Our Repository",
  politica:"Privacy Policy",
  download: "Download on",
  equipo:"Team",
  equipoHead:"Meet the Hacks Costeños team",
  nathan:"Programming and Hardware",
  ashlee:"Web and Planning",
  felipe:"Editing and Design",
  herramientas:"Tools",
  herramientasHead:"Technologies we use",
  enlaces:"Links",
  inicio:"Home",
  mision:"Mission",
  nosotros:"About Us"
 },
 fr: {
  slogan: "Élevant la sécurité des Colombiens à un autre niveau !",
  knowButton: "Découvrez notre projet",
  header1: "La prévention et l'information sont la clé",
  p1: "Niveles de Niveles est une plateforme qui utilise la prévention et l'information comme les outils les plus importants pour lutter contre les catastrophes naturelles. Nous créons un environnement sécurisé où les utilisateurs ont la possibilité de signaler, d'être alertés et d'être informés des niveaux de risque de catastrophes naturelles autour d'eux. Préparez-vous en utilisant notre",
  guia: "guide des catastrophes",
  sensorsHeader: "Nos capteurs",
  sensorText: "Nous utilisons des capteurs pour mesurer le niveau de l'eau et le mouvement de la terre afin de déterminer le risque d'inondations et de glissements de terrain.",
  crowdHeader: "Crowdsourcing",
  crowdText: "Nous utilisons un modèle de collaboration ouverte (crowdsourcing) pour obtenir des rapports de catastrophes de la population elle-même.",
  desastres: "Catastrophes naturelles",
  desastresHeader: "Les catastrophes que nous prévenons sont",
  desbordamientoHead: "Débordements",
  desbordamientoText: "Le débordement des rivières, des ruisseaux et d'autres cours d'eau provoque des inondations dans différents municipalités de l'Atlantique. Avoir un mécanisme qui alerte à ce sujet donnerait aux communautés avoisinantes le temps de rassembler leurs biens les plus importants et d'éviter des dommages majeurs à leurs habitations. Pour mesurer cela, nous utilisons des capteurs ultrasoniques pour mesurer le niveau de l'eau.",
  incendioHead: "Incendies de forêt",
  incendioText: "Dans les Caraïbes colombiennes, 150 incendies de forêt ont été signalés cette année, principalement causés par des températures élevées et des pluies rares. Une fois que ces incendies atteignent une ampleur telle qu'il peut prendre des jours pour les arrêter, les signaler le plus rapidement possible facilitera la prévention de la destruction de la faune environnante.",
  deslizamientoHead: "Glissements de terrain",
  deslizamientoText: "Entre 1920 et 2020, plus de 11 800 glissements de terrain ont été enregistrés, mais seulement 813 ont eu lieu en 2022. C'est une preuve de la manière dont le changement climatique affecte le pays. Beaucoup de gens ne savent pas qu'ils se trouvent dans une zone à risque, donc recevoir une alerte sur le mouvement de la terre peut aider les communautés à éviter des catastrophes. Nous utilisons des accéléromètres pour mesurer le mouvement de la terre.",
  recursos: "Ressources",
  recursosHead: "Intéressé ? Jetez un œil à certains de nos progrès",
  repo: "Notre dépôt",
  politica: "Politique de confidentialité",
  download: "Téléchargez-le sur",
  equipo: "Équipe",
  equipoHead: "Rencontrez l'équipe Hacks Costeños",
  nathan: "Programmation et matériel",
  ashlee: "Web et planification",
  felipe: "Édition et conception",
  herramientas: "Outils",
  herramientasHead: "Technologies que nous utilisons",
  enlaces: "Liens",
  inicio: "Accueil",
  mision: "Mission",
  nosotros: "À propos de nous"

 },
 zh: {
  slogan: "将哥伦比亚人的安全提升到另一个水平！",
   knowButton: "了解我们的项目",
   header1: "预防和信息是关键",
   p1: "Niveles de Niveles 是一个利用预防和信息作为对抗自然灾害最重要工具的平台。我们创造了一个安全的环境，用户可以选择报告，接收警报并了解周围自然灾害风险水平。通过使用我们的",
   guia: "灾难指南",
   sensorsHeader: "我们的传感器",
   sensorText: "我们使用传感器测量水位和地壳运动，以确定洪水和滑坡的风险。",
   crowdHeader: "众包",
   crowdText: "我们采用开放协作模式（众包）获取人口自身的灾难报告。",
   desastres: "自然灾害",
   desastresHeader: "我们防范的灾害有",
   desbordamientoHead: "溢出",
   desbordamientoText: "河流、小溪和其他水体的溢出在大西洋不同的市镇引发了洪水。具备能够提前警报的机制将为附近社区争取时间，使其能够整理重要物品，避免房屋受到严重损害。我们使用超声波传感器测量水位以进行这方面的测量。",
   incendioHead: "森林火灾",
   incendioText: "今年，哥伦比亚加勒比地区报告了150起森林火灾，主要原因是高温和降雨稀少。一旦这些火灾达到一个规模，以至于需要数天才能扑灭，尽早报告将更容易防止周围动植物的破坏。",
   deslizamientoHead: "滑坡",
   deslizamientoText: "在1920年到2020年期间，记录了超过11,800起山体滑坡，但仅在2022年发生了813起。这是气候变化如何影响该国的证据。许多人不知道他们处于危险区域，因此提前接收地壳运动警报可以帮助社区避免灾难。我们使用加速度计测量地壳运动。",
   recursos: "资源",
   recursosHead: "感兴趣吗？看看我们的一些进展",
   repo: "我们的存储库",
   politica: "隐私政策",
   download: "下载地址：",
   equipo: "团队",
   equipoHead: "认识 Hacks Costeños 团队",
   nathan: "编程和硬件",
   ashlee: "Web 和规划",
   felipe: "编辑和设计",
   herramientas: "工具",
   herramientasHead: "我们使用的技术",
   enlaces: "链接",
   inicio: "首页",
   mision: "使命",
   nosotros: "关于我们"
 }
});