import LocalizedStrings from 'react-localization';

export const Localizations = new LocalizedStrings({
 es:{
   slogan: "Llevando la seguridad de los colombianos a otro nivel!",
   knowButton: "Conóce nuestro proyecto",
   header1: "La prevención y la información es la clave",
   p1: "Niveles de Niveles es una plataforma que utiliza la prevención y la información como la herramienta más importante para combatir desastres naturales. Creamos un ambiente seguro donde los usuarios tienen la opción de reportar, ser alertados y estar informados sobre los niveles de riesgo de desastres naturales a su alrededor. Prepárate utilizando nuestra",
   guia:"guía para desastres",
   sensorsHeader: "Nuestros Sensores",
   sendorText:"Utilizamos sensores para medir el nivel del agua y el movimiento de la tierra y así determinar el riesgo de desbordamientos y deslizamientos.",
   crowdHeader: "Crowdsourcing",
   crowdText: "Utilizamos un modelo de colaboración abierta (crowdsourcing) para obtener los reportes de desastres de la misma población.",
   desastres: "Desastres Naturales",
   desastresHeader: "Los desastres que prevenimos son",
   desbordamientoHead: "Desbordamientos",
   desbordamientoText: "El desbordamiento de ríos, arroyos y otros cuerpos de agua causan inundaciones en diferentes municipios del Atlántico. Tener un mecanismo que alerte sobre estos les daría a las comunidades cercanas tiempo para recoger sus pertenencias más importantes y evitar daños mayores en sus viviendas. Para medir estos, utilizamos sensores ultrasónicos para medir el nivel del agua.",
   incendioHead: "Incendios Forestales",
   incendioText: "En el Caribe colombiano se han reportado 150 incendios forestales este año y su causa principal son las altas temperaturas y las escasas lluvias. Una vez que estos llegan a un punto que su magnitud es tan grande que puede llevar días para detenerlo, por lo que si logramos reportar estos en el menor tiempo posible, será más fácil evitar la destrucción de la fauna a su alrededor.",
   deslizamientoHead: "Deslizamientos",
   deslizamientoText: "Entre 1920 y 2020, se registraron más de 11.800 deslizamientos de tierra, pero solamente en 2022 se dieron 813. Esto es una prueba de cómo el cambio climático está afectando al país. Hay muchas personas que no saben que están en una zona de riesgo por lo que el tener una alerta sobre el movimiento de la tierra puede ayudar a las comunidades a evitar catástrofes. Utilizamos acelerómetros para medir el movimiento de la tierra.",
   recursos:"Recursos",
   recursosHead:"¿Te interesa? Mira un poco de nuestros avances",
   repo:"Nuestro Repositorio",
   politica:"Política de Privacidad",
   equipo:"Equipo",
   equipoHead:"Cónoce al equipo Hacks Costeños",
   nathan:"Programación y Hardware",
   ashlee:"Web y Planeación",
   felipe:"Edición y Diseño",
   herramientas:"Herramientas",
   herramientasHead:"Tecnologías que utilizamos",
   enlaces:"Enlaces",
   inicio:"Inicio",
   mision:"Misión",
   nosotros:"Nosotros"
 },
 en: {
slogan: "",
   knowButton: "",
   header1: "",
   p1: "",
   sensorsHeader: "",
   sendorText:"",
   crowdHeader: "",
   crowdText: "",
   desastres: "",
   desastresHeader: "",
   desbordamientoHead: "",
   desbordamientoText: "",
   incendioHead: "",
   incendioText: "",
   deslizamientoHead: "",
   deslizamientoText: "",
   recursos:"",
   recursosHead:"",
   repo:"",
   politica:"",
   equipo:"",
   equipoHead:"",
   nathan:"",
   ashlee:"",
   felipe:"",
   herramientas:"",
   herramientasHead:"",
   enlaces:"",
   inicio:"",
   mision:"",
   nosotros:""
 },
 fr: {
    slogan: "",
    knowButton: "",
    header1: "",
    p1: "",
    sensorsHeader: "",
    sendorText:"",
    crowdHeader: "",
    crowdText: "",
    desastres: "",
    desastresHeader: "",
    desbordamientoHead: "",
    desbordamientoText: "",
    incendioHead: "",
    incendioText: "",
    deslizamientoHead: "",
    deslizamientoText: "",
    recursos:"",
    recursosHead:"",
    repo:"",
    politica:"",
    equipo:"",
    equipoHead:"",
    nathan:"",
    ashlee:"",
    felipe:"",
    herramientas:"",
    herramientasHead:"",
    enlaces:"",
    inicio:"",
    mision:"",
    nosotros:""

 },
 zh: {
     slogan: "",
   knowButton: "",
   header1: "",
   p1: "",
   sensorsHeader: "",
   sendorText:"",
   crowdHeader: "",
   crowdText: "",
   desastres: "",
   desastresHeader: "",
   desbordamientoHead: "",
   desbordamientoText: "",
   incendioHead: "",
   incendioText: "",
   deslizamientoHead: "",
   deslizamientoText: "",
   recursos:"",
   recursosHead:"",
   repo:"",
   politica:"",
   equipo:"",
   equipoHead:"",
   nathan:"",
   ashlee:"",
   felipe:"",
   herramientas:"",
   herramientasHead:"",
   enlaces:"",
   inicio:"",
   mision:"",
   nosotros:""
 }
});