import LocalizedStrings from 'react-localization';

export const Localizations = new LocalizedStrings({
 es:{
   slogan: "",
   knowButton: "",
   header1: "",
   p1: "",
   sensorsHeader: "",
   sendorText:"",
   crowdHeader: "",
   crowdText: "",
   desastres: "",
   desastresHeader: "",
   desbordamientoHead: "",
   desbordamientoText: "",
   incendioHead: "",
   incendioText: "",
   deslizamientoHead: "",
   deslizamientoText: "",
   recursos:"",
   recursosHead:"",
   repo:"",
   politica:"",
   equipo:"",
   equipoHead:"",
   nathan:"",
   ashlee:"",
   felipe:"",
   herramientas:"",
   herramientasHead:"",
   enlaces:"",
   inicio:"",
   mision:"",
   nosotros:""
 },
 en: {
    slogan: "",
   knowButton: "",
   header1: "",
   p1: "",
   sensorsHeader: "",
   sendorText:"",
   crowdHeader: "",
   crowdText: "",
   desastres: "",
   desastresHeader: "",
   desbordamientoHead: "",
   desbordamientoText: "",
   incendioHead: "",
   incendioText: "",
   deslizamientoHead: "",
   deslizamientoText: "",
   recursos:"",
   recursosHead:"",
   repo:"",
   politica:"",
   equipo:"",
   equipoHead:"",
   nathan:"",
   ashlee:"",
   felipe:"",
   herramientas:"",
   herramientasHead:"",
   enlaces:"",
   inicio:"",
   mision:"",
   nosotros:""
 },
 fr: {
    slogan: "",
    knowButton: "",
    header1: "",
    p1: "",
    sensorsHeader: "",
    sendorText:"",
    crowdHeader: "",
    crowdText: "",
    desastres: "",
    desastresHeader: "",
    desbordamientoHead: "",
    desbordamientoText: "",
    incendioHead: "",
    incendioText: "",
    deslizamientoHead: "",
    deslizamientoText: "",
    recursos:"",
    recursosHead:"",
    repo:"",
    politica:"",
    equipo:"",
    equipoHead:"",
    nathan:"",
    ashlee:"",
    felipe:"",
    herramientas:"",
    herramientasHead:"",
    enlaces:"",
    inicio:"",
    mision:"",
    nosotros:""

 },
 zh: {
    slogan: "",
   knowButton: "",
   header1: "",
   p1: "",
   sensorsHeader: "",
   sendorText:"",
   crowdHeader: "",
   crowdText: "",
   desastres: "",
   desastresHeader: "",
   desbordamientoHead: "",
   desbordamientoText: "",
   incendioHead: "",
   incendioText: "",
   deslizamientoHead: "",
   deslizamientoText: "",
   recursos:"",
   recursosHead:"",
   repo:"",
   politica:"",
   equipo:"",
   equipoHead:"",
   nathan:"",
   ashlee:"",
   felipe:"",
   herramientas:"",
   herramientasHead:"",
   enlaces:"",
   inicio:"",
   mision:"",
   nosotros:""
 }
});