enum STATUS_CODES {
    SUCCESS,
    GENERIC_ERROR,
    USER_NOT_FOUND,
    INVALID_NUMBER,
    SENT_CODE,
    NUMBER_NOT_EXIST,
    ERROR_SENDING_CODE,
    TOO_MANY_ATTEMPTS,
    CODE_DENIED,
    CODE_EXPIRED,
    CODE_FAILED,
    ALREADY_REPORTED,
    MISMATCHED_IMAGE,
}
export default STATUS_CODES;